// <auto-generated />
namespace Mooshak2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial17));
        
        string IMigrationMetadata.Id
        {
            get { return "201605131611154_initial17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
